### ISSUE TITLE
Archive this repo to reflect migration from Sheriff to CLOWarden

### ISSUE THREAD

**Issue by RobertKielty** [cncf/sheriff#14]
Sheriff is no longer being used to manage access to repos in the CNCF Github Org.

CLOWarden has been deployed and will continue to be actively developed in order to manage CNCF org repo access.

Track archiving this repository and documenting the transition that has taken place.

```[tasklist]
### Tasks
- [ ] Update the cncf/sheriff README
- [ ] For each open issue here, close or transfer to the CLOWarden repo
- [ ] Archive this repo
```
